simpledotorg/bp-passport

src/Navigation.tsx
src/components/index.ts
src/components/text.tsx
src/screens/ConsentScreen.tsx
src/screens/SplashScreen.tsx
src/translations/strings_en.json

Consent screen

---

package.json
src/App.tsx
src/Navigation.tsx
src/api/auth.ts
src/api/blood-pressures.ts
src/api/constants.ts
src/api/facilities.ts
src/api/index.ts
src/screens/LaunchScreen.tsx
src/screens/ScanPassportScreen.tsx
src/screens/SplashScreen.tsx
yarn.lock

WIP: API set up

---

src/screens/SettingsScreen.tsx
yarn.lock

This PR changes the language settings on the settings screen to use the 4 language options regardless if they are on the device or not.

Fix Language Setting Options

---

src/screens/LoginScreen.tsx

Using alert over the custom modal

---

src/components/bp-information.tsx
src/screens/BpHistoryScreen.tsx
src/screens/HomeScreen.tsx
src/screens/ScanPassportScreen.tsx
src/screens/SettingsScreen.tsx

Bug fixes for:
- Terms and conditions link going to the wrong URL:
https://trello.com/c/s3mh1CDP/55-bug-settings-screen-ios-terms-conditions-link-does-not-work
- No blood pressure was showing no grey heart and information regarding no blood readings:
https://trello.com/c/54hb5NDP/53-bug-home-screen-when-user-has-no-blood-pressure-readings-grey-heart-icon-is-not-displaying
- Spacing issue:
https://trello.com/c/wNTZ3TuX/52-bug-home-screen-spacing-between-name-and-bp-passport-information-needs-to-be-increased
- All BP scrolling:
https://trello.com/c/znawGF6Q/54-bug-all-my-bp-screen-is-not-scrollable-to-view-older-bp-readings

Quick bugs

---

android/app/build.gradle
ios/BPPassport.xcodeproj/project.pbxproj
mock-api/responses/patient/get200.json
src/App.tsx
src/Navigation.tsx
src/api/patient.ts
src/components/home-header.tsx
src/models/index.ts
src/models/medication.ts
src/offline/database.ts
src/providers/auth.provider.tsx
src/providers/user.provider.tsx
src/screens/HomeScreen.tsx
src/screens/ScanPassportScreen.tsx

User, Blood Pressures and Medications are now all loaded in from API and also now saved to disk for instant, offline home screen data access.
https://trello.com/c/YbJbKmFC/23-patient-home-screen-my-medicines
https://trello.com/c/Qnv43US9/2-plan-architect-an-offline-first-data-model

Offline data + Medications

---

src/components/button.tsx
src/screens/HomeScreen.tsx
src/styles/colors.ts

Description:
This PR adds the correct shadows to the button component
Ticket:
https://trello.com/c/AdGxrnQ9/156-bug-button-styling
Screenshots:

Button shadows

---

src/redux/medication/medication.actions.ts
src/redux/medication/medication.models.ts
src/screens/MedicineFrequencyScreen.tsx

https://trello.com/c/dl4Br21c/184-bug-medicine-reminders-reminders-are-triggering-on-incorrect-days
https://trello.com/c/685oxmgX/183-bug-ios-medicine-detail-view-set-time-wheel-not-showing-when-changing-reminder-time

Reminders fixes

---

src/redux/blood-sugar/blood-sugar.models.ts
src/screens/AddBsScreen.tsx
src/translations/strings_es.json
src/translations/strings_fr.json
src/translations/strings_hi_IN.json
src/translations/strings_mr_IN.json
src/translations/strings_pa_IN.json
src/utils/blood-sugars.ts
translations/master.json

Change a pretty weird typo which was visible

Change typo

---

src/components/bp-modal.tsx
src/components/bs-modal.tsx
src/redux/blood-sugar/blood-sugar.models.ts
src/screens/AddBsScreen.tsx
src/screens/BsHistoryScreen.tsx
src/translations/strings_es.json
src/translations/strings_fr.json
src/translations/strings_hi_IN.json
src/translations/strings_mr_IN.json
src/translations/strings_pa_IN.json
src/utils/blood-sugars.ts
translations/master.json

Removes the BS chart because it is not ready.
Fix a few bugs, fix percentages for HbAc1 and fix dates

Remove BS chart

---

src/components/home-header.tsx
src/redux/auth/auth.models.ts
src/redux/auth/auth.reducer.ts
src/redux/auth/auth.selectors.ts
src/screens/MedicineFrequencyScreen.tsx

https://trello.com/c/rQnXlLyq/189-bug-medicines-user-shouldnt-be-able-to-unselect-all-days-in-frequency-multi-select
https://trello.com/c/rjsP9kfV/201-bug-home-ios-spanish-bp-passport-logo-shouldnt-be-translated-it-should-always-read-bp-passport

Medicine days and others

---

src/components/bp-history-chart.tsx
src/components/bs-history-chart.tsx
src/screens/BsHistoryScreen.tsx
src/utils/data-transform.ts
src/utils/dates.ts

Blood sugar charts and refactor

Blood sugar charts

---

src/screens/AddBpScreen.tsx

**Description:**
This PR changes both keyboards used in the add bp screen to use the numeric keyboard type.

change BP keyboards

---

src/components/bs-history-chart.tsx

Don't show pills for values which do not exist

Only show appropriate pulls

---

src/screens/AddBsScreen.tsx

This PR changes the Add BS screen to use a scrollview.

change bs view to scrollview

---

translations/master.json

Updated `bs.hemoglobic` string from "Hemoglobic" to "Hemoglobin"

Updated Hemoglobin string

---

src/components/bs-modal.tsx

This PR adds the units of measurement to the normal/high notes in the BS modal.

add units correctly

---

translations/master.json

Adding new copy to include in Consent and Settings screens. Will update designs in Figma and upload to Zeplin.

Added medical disclaimer copy

---

src/components/bp-history-chart.tsx
src/components/bp-information.tsx
src/components/bp-modal.tsx
src/components/bs-history-chart.tsx
src/utils/blood-sugars.ts

Update time to display on BP and BS 

---

src/screens/BpHistoryScreen.tsx
src/screens/BsHistoryScreen.tsx
src/screens/HomeScreen.tsx

This PR fixes the key warnings from lists

Missing key warnings

---

src/components/bs-history-chart.tsx

This PR fixes an issue where there was an empty axis causing a white line to overlap data points.

remove empty axis

---

src/screens/BpHistoryScreen.tsx
src/screens/BsHistoryScreen.tsx

This PR fixes the centered scroll bar issue appearing on devices running iOS 13.

I10 scroll bar bug

---

src/screens/AddBpScreen.tsx
src/screens/AddBsScreen.tsx
src/screens/SettingsScreen.tsx

This PR changes the review logic to work with high/low values, it only doesn't count very high/low values (which display a warning modal)
Stop settings write review button from not being visible.

change review logic

---

src/redux/auth/auth.actions.ts

https://trello.com/c/9A4r6yRo/298-connect-to-bp-passport-firebase-analytics-event

Firebase analytics - connect to bp passport

---

src/components/health-reminders/health-reminder.tsx
src/components/health-reminders/health-reminders.tsx
src/screens/HomeScreen.tsx

https://trello.com/c/Vm6plsJl/292-patient-health-reminder-cards-update-ui

292-patient-health-reminder-cards-update-ui

---

src/components/bp-modal.tsx
src/components/bs-modal.tsx
src/screens/DetailsModalScreen.tsx
src/screens/ScanPassportScreen.tsx
src/utils/device.ts

https://trello.com/c/xOiT52Ci/281-patient-bp-bs-details-sheet-update-ui

281-patient-bp-bs-details-sheet-update-ui

---

src/components/bp-history-chart.tsx
src/components/bp-history/chart-data.ts
src/components/bp-history/chart-request.ts
src/components/victory-chart-parts/date-axis-component.tsx
src/components/victory-chart-parts/date-axis.ts
src/components/victory-chart-parts/month-name-label.tsx
src/screens/ScanPassportScreen.tsx
src/utils/dates.ts

https://trello.com/c/KIT10FKi/302-patient-blood-pressure-graph-4-months-of-data

302-patient-blood-pressure-graph-4-months-of-data

---

src/components/bs-modal.tsx

https://trello.com/c/xOiT52Ci/281-patient-bp-bs-details-sheet-update-ui

281-patient-bp-bs-details-sheet-update-ui update

---

src/components/bp-history-chart.tsx
src/components/bs-history-chart.tsx
src/components/bs-history/chart-data.ts
src/components/bs-history/i-define-a-chart-request.ts
src/components/bs-history/scatter-graph-data-point.ts
src/components/victory-chart-parts/victory-graph-tool-tip-helper.tsx
src/utils/blood-sugars.ts

https://trello.com/c/tI6Lj6JX/280-patient-blood-sugar-graphs-update-ui

280-patient-blood-sugar-graphs-update-ui

---

src/screens/SettingsScreen.tsx
src/utils/blood-sugars.ts

https://trello.com/c/OnyLiepm/300-patient-add-blood-sugar-update-blood-sugar-units

300-patient-add-blood-sugar-update-blood-sugar-units

---

src/screens/AddBsScreen.tsx
src/screens/AddDataWarningModalScreen.tsx

https://trello.com/c/Wd69Kb5R/282-patient-blood-sugar-alert-general-modals-update-ui

282-patient-blood-sugar-alert-general-modals-update-ui

---

src/components/bp-information.tsx
src/components/bs-history-chart.tsx
src/components/bs-information.tsx
src/utils/blood-sugars.ts

https://trello.com/c/EDx02LJ7/299-patient-blood-sugar-rows-update-ui

299-patient-blood-sugar-rows-update-ui

---

src/screens/AddBpScreen.tsx
src/screens/AddBsScreen.tsx

https://trello.com/c/BlVvZ31u/293-patient-add-bp-bs-figma-styling-issue

293-patient-add-bp-bs-figma-styling-issue

---

src/components/bs-modal.tsx
src/redux/blood-sugar/blood-sugar.models.ts
src/screens/AddBsScreen.tsx
src/utils/blood-sugars.ts

I12 final fixes
